name: QuickDryCleaningData

on:
  schedule:
    - cron: '33 3-15/1 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: developer
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Schedule Heartbeat
        run: |
          # Set the timezone to IST and print the current time
          export TZ="Asia/Kolkata"
          echo "Heartbeat: Workflow triggered at $(date +'%Y-%m-%d %H:%M:%S') IST"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Create Output Directory
        run: mkdir -p src/main/resources/Output/

      - name: Run Selenium Scraper
        run: mvn compile exec:java -D"exec.mainClass"="org.testing.Main"
        env:
          USER_ID: ${{ secrets.SCRAPE_USER }}
          USER_PASS: ${{ secrets.SCRAPE_PASS }}
          USER_CODE: ${{ secrets.SCRAPE_CODE }}
          CHROME_OPTIONS: "--headless --disable-gpu --no-sandbox"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
      
          git add src/main/resources/Output/
          
          if ! git diff --cached --quiet; then
              echo "Changes detected in Output folder. Committing updates..."
              git commit -m "Automated update: OrderReport and Branch APIs"
              git pull --rebase origin $BRANCH
              git push origin $BRANCH
          else
              echo "No changes detected in the target path. Skipping push."
          fi
